version: '3'

services:
  php:
    build: .
    container_name: php
    volumes:
      - .:/app
    ports:
      - 80:80
    command: "php -S 0.0.0.0:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306
